service: SES

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  stage: dev
  timeout: 60
  environment:
    SESSION_NAME: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  send-email:
    timeout: 10
    memorySize: 128
    handler: src/send-email.handler
    events:
    - http:
        path: send-email
        method: post
        cors: true
